#!/usr/bin/env bash
# A bash script that Displays a list of currently running processes, it:
#  show all processes, for all users, including those which might not have a TTY
#  display a user-oriented format
#  show process hierarchy

ps axuf
