#!/usr/bin/env bash
# script that loops from 1 to 10 and displays and
#   "bad luck" for the 4th loop iteration
#   "good luck" for the 8th loop iteration
#   "Holberton School" for the other iterations

COUNT=1
while [ "$COUNT" -le 10 ]; do
    if [ $COUNT -eq 4 ]; then
     echo "bad luck"
    elif [ $COUNT -eq 8 ]; then
     echo "good luck"
    else
     echo "Holberton School"
    fi
    let COUNT=COUNT+1
done
